@startuml
actor DataScientist as DS

rectangle "Population Report System" {
    usecase "Produce a report on the top N populated \ncountries in the world where N is provided by the user" as UC4
    usecase "Produce a report on the top N populated \ncountries in a continent where N is provided by the user" as UC5
    usecase "Produce a report on the top N populated \ncountries in a region where N is provided by the user" as UC6
}

DS --> UC4
DS --> UC5
DS --> UC6

@enduml
