@startuml
left to right direction
actor "Data Scientist" as DS

rectangle "Population Report System" {
  usecase "Top N Populated Capital Cities in World" as UC20
  usecase "Top N Populated Capital Cities in Continent" as UC21
  usecase "Top N Populated Capital Cities in Region" as UC22
}

DS --> UC20
DS --> UC21
DS --> UC22

@enduml
