@startuml
left to right direction
actor "Data Scientist" as DS

rectangle "Population Data System" {
    usecase "Produce a report on the top N populated cities in the world" as UC12
    usecase "Produce a report on the top N populated cities in a continent" as UC13
    usecase "Produce a report on the top N populated cities in a region" as UC14
    usecase "Produce a report on the top N populated cities in a country" as UC15
    usecase "Produce a report on the top N populated cities in a district" as UC16
}

DS --> UC12
DS --> UC13
DS --> UC14
DS --> UC15
DS --> UC16

@enduml
