name: A workflow for Group 4
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn compile
      - name: Build with Maven
        run: mvn package
      - name: Run docker compose
        run: docker compose up --abort-on-container-exit

